### PR TITLE
refactor: switch to count due the for_each limitations

### PR DESCRIPTION
**Pull request by SweetOps**
## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

### CODE REVIEW

**Comment by 1david5** [comment]
Hi @SweetOps, 

First, I want to thank you for the contributions to this project. I have been following this draft PR for a couple of days because I was planning to propose similar changes since I think it will resolve some issues I'm facing when creating rules with `source_security_group_id` and `self`. I wanted to reach out to you to know if there is anything I can help with in order to release it or if maybe you have an estimate time for its release.

**Comment by SweetOps** [comment]
hey @1david5, I'll close this PR soon in favour of another one cos I found the another way how to trick `terraform` logic :smile:. And I hope that I'll introduce pretty fix on this weekends.  

> First, I want to thank you for the contributions to this project. 

 :pray: ❤️

**Comment by 1david5** [comment]
Thank you for the update @SweetOps. I’m positive about these fixes. Looking forward to start using them soon. 😃 👍

**Comment by SweetOps** [comment]
closed in favour of https://github.com/cloudposse/terraform-aws-security-group/pull/11

**Pull request closed without merging**
