### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Fix empty target_security_group_id

## why
* If this is empty, it will throw an error

## references
- N/A

### CODE REVIEW

**Comment by Nuru** [comment]
If `local.create_security_group` is `false` then this module is not creating a security group and it is therefore an error to not supply a `target_security_group_id`. This is intentional.

**Comment by nitrocode** [comment]
What variable in the sg export should be mapped to the `target_security_group_id` ?

**Comment by Nuru** [comment]
> What variable in the sg export should be mapped to the `target_security_group_id` ?

None. Other Cloud Posse modules using this module should, in general, either create a security group or accept an already configured security group. If another module were to accept a security group ID and then use this module to modify the security group, this would likely cause flapping between the configuration of the security group in that module and the configuration in whatever module created the security group. 

Every Cloud Posse module should output enough information for the user to configure any security group they want to work with the resources created by that module. If we find a use case where it is appropriate for the module to modify the security group it is given, we can address that as a special case.

**Pull request closed without merging**
